import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import Navbar from '@/components/navbar';
import { AuthProvider } from '@/components/auth-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			suppressHydrationWarning={true}
			className='w-full h-full max-w-full max-h-full'
			lang='en'>
			<body
				suppressHydrationWarning={true}
				className={
					inter.className + ' w-full h-full max-w-full max-h-full'
				}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange>
					<AuthProvider>
						<Navbar />
						{children}
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
